FROM python:3.10
WORKDIR /app
ENV PYTHONPATH=/app

COPY requirements.txt .
RUN pip install -r requirements.txt
COPY backend/ ./backend
COPY common/ ./common
COPY auth/ ./auth
EXPOSE 9876
#CMD ["mkdir", "./common/temp_files"]
CMD ["python", "./backend/backend_webserver.py"]