version: "3.8"
name: spotify_stats
services:
  mysql:
    restart: always
    build: ./mysql/
    container_name: mysql
    # image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: 'spotify_stats'
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_TCP_PORT: 3307
  pythonapp:
    # image: python:3.8-alpine
    container_name: spotify_stats_python
    # links:
    depends_on:
      - mysql
    build:
      context: ../
      dockerfile: ./docker/python/Dockerfile
    #./python/
    ports:
      - "5001:5000"