name: Build and push backend Docker image

on:
  push:
    branches:
      - refactor # Triggert den Workflow bei jedem Push in den main Branch
  # Optional können Sie auch für Pull Requests den Workflow triggern
  pull_request:
    branches:
      - main

jobs:
  build_and_push_backend_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Prepare lowercase repository owner
        id: prep
        run: echo "lowercase_owner=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./backend/Dockerfile-backend #Pfad zum Dockerfile-Backend; stellen Sie sicher, dass dieser korrekt ist.
          push: true
          tags: ghcr.io/${{ env.lowercase_owner }}/backend:${{ github.sha }}
